name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: cd hw1 && cd build && cmake -DCMAKE_CXX_FLAGS="-Werror" ..
    - name: make
      run: cd hw1/build && ls -la && make
